[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "isaac_core_dev_kit"
version = "1.0.0"
description = "A development kit for running Isaac Sim, capturing data, and sending UDP commands, using the isaac_core_2023 repo."
authors = [
    { name="Maple Office", email="mapleoffice@atomicmail.io" }
]
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }

dependencies = []

[tool.setuptools.packages.find]
where = ["."]
include = ["isaac_core_dev_kit*"]
